version: 2
jobs:
  build:
    working_directory: ~/opengb-dram
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: dram-{{ checksum "deps.edn" }}
      - run: clojure -P
      - save_cache:
          paths:
            - ~/.m2
          key: dram-{{ checksum "deps.edn" }}
      - run: clojure -A:test
